stages:
  - linter

hadolint:
  stage: linter
  image: hadolint/hadolint:latest-debian
  script:
    - | 
      hadolint --ignore DL3018 --ignore DL3019 Dockerfile

kube-linter:
  stage: linter
  image: stackrox/kube-linter:0.1.4
  script:
    - kube-linter lint $CI_PROJECT_NAME