name: LINTER
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  hadolint:
    name: Linter dockerfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install hadolint
      continue-on-error: true
      run: docker run --rm -i hadolint/hadolint < Dockerfile

  kubelinter:
    name: Linter kubernetes
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Scan repo with kube-linter Actions
      uses: stackrox/kube-linter-action@v1.0.4
      continue-on-error: true
      with:
        directory: cicd-linter
        format: sarif
        output-file: kube-linter.sarif
    - name: Scan repo with kube-linter Docker
      continue-on-error: true
      run: |
       export REPO_NAME=${{ github.event.repository.name }}
       echo $REPO_NAME
    #    docker run -v $(PWD):/dir stackrox/kube-linter lint --format json /dir/$REPO_NAME > kube-linter.json
    # - uses: actions/upload-artifact@v2
    #   name: upload kubelinter report
    #   with:
    #     name: kubelinter
    #     path: kube-linter.json
    # - name: Upload kubelinter scan results to GitHub tab
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: 'kube-linter.sarif'
