name: LINTER
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  hadolint:
    name: Linter dockerfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install hadolint
      run: docker run --rm -i hadolint/hadolint < Dockerfile

  kubelinter:
    name: Linter kubernetes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Scan yamls
      id: kube-lint-scan
      uses: stackrox/kube-linter-action@v1
      with:
        directory: cicd-linter
        config: .kube-linter/config.yaml

